### ISSUE TITLE
Error cross compiling from linux/amd64 to arm

### ISSUE THREAD

**Issue by fmpwizard** [tarm/goserial#15]
Hi,

I setup my dev env to cross compile, my host is linux amd64 and trying to cross compile to arm givesme:

```
GOOS=linux GOARCH=arm go build
# github.com/huin/goserial
./serial.go:151: undefined: openPort
./serial.go:151: not enough arguments to return

```

but  `GOOS=windows go build`
builds fine and I end up with a `exe` binary of my project

if I compile from an arm (raspbery pi), it compiles fine. Any idea of what I may be missing?

Thanks

**Comment by tarm** [comment]
@fmpwizard Are you using this repo or the huin version?

It builds for me locally:
~/go/src/github.com/tarm/goserial (master %)$ GOOS=linux GOARCH=arm go build
~/go/src/github.com/tarm/goserial (master %)$

Please try with this repo (tarm/goserial) and reopen the issue if needed.
